const translations = {
  en: {
    nav_home: "Home",
    nav_about: "About Us",
    nav_links: "Links",
    nav_blogs: "Blogs",

    hero_title: "S&N LOGISTICS LLC",
    hero_subtitle: "Your Trusted Partner in International Shipping",
    hero_desc:
      "We provide comprehensive logistics solutions for air, sea, rail, and road freight worldwide.",
    btn_started: "Get Started",
    btn_learn: "Learn More",

    serv_main_title: "Our Services",
    serv_main_desc: "Comprehensive shipping solutions tailored to your needs",

    serv_sea_title: "Sea Freight",
    serv_sea_desc: "Cost-effective ocean shipping for large cargo volumes",
    serv_sea_li1: "FCL & LCL Shipments",
    serv_sea_li2: "Port to Port / Door to Door",
    serv_sea_li3: "Customs Clearance",
    serv_sea_li4: "Cargo Insurance",

    serv_air_title: "Air Freight",
    serv_air_desc:
      "Fast and reliable air transportation for time-sensitive shipments",
    serv_air_li1: "Express Delivery",
    serv_air_li2: "Consolidated Cargo",
    serv_air_li3: "Dangerous Goods Handling",
    serv_air_li4: "Real-time Tracking",

    serv_rail_title: "Rail Freight",
    serv_rail_desc: "Efficient rail transport across continents",
    serv_rail_li1: "Container Transport",
    serv_rail_li2: "Intermodal Services",
    serv_rail_li3: "Cross-border Delivery",
    serv_rail_li4: "Cost-effective Solutions",

    serv_road_title: "Road Freight",
    serv_road_desc: "Flexible door-to-door delivery solutions",
    serv_road_li1: "Local & International",
    serv_road_li2: "Temperature Controlled",
    serv_road_li3: "Specialized Transport",
    serv_road_li4: "Last-mile Delivery",

    gal_title: "Gallery",
    gal_desc: "Our operations around the world",
    gal_img1_title: "Cargo Loading",
    gal_img1_desc: "Secure packaging solutions",
    gal_img2_title: "Container Stuffing",
    gal_img2_desc: "Professional cargo handling",
    gal_img3_title: "Quality Inspection",
    gal_img3_desc: "Safety and compliance checks",
    gal_img4_title: "Heavy Equipment Transport",
    gal_img4_desc: "Specialized machinery shipping",
    gal_img5_title: "Vehicle Logistics",
    gal_img5_desc: "Safe automobile transportation",
    gal_img6_title: "Cargo Supervision",
    gal_img6_desc: "Expert loading monitoring",

    cont_title: "Get in Touch",
    cont_desc: "Have questions? We'd love to hear from you.",
    cont_info_title: "Contact Information",
    cont_addr_label: "Address",
    cont_phone_label: "Phone",
    cont_email_label: "Email",

    footer_contact_title: "Contact",
    footer_addr_val: "Poti, Georgia",
    footer_links_title: "Useful Links",
    footer_rights: "© 2026 S&N Logistics LLC. All rights reserved.",

    about_main_title: "About Us",
    about_main_desc:
      "S&N LOGISTICS LLC is a dynamic and rapidly growing logistics company based in Poti, Georgia. We specialize in providing comprehensive shipping and logistics solutions to clients across the globe. Our mission is to simplify the complexities of international trade by offering reliable, efficient, and cost-effective services tailored to meet the unique needs of each customer.",
    why_choose_title: "Why Choose S&N LOGISTICS LLC?",
    why_choose_desc:
      "At S&N LOGISTICS LLC, we understand that every shipment matters. That’s why we’ve built our reputation on reliability, transparency, and unparalleled customer service. From the moment you contact us to the final delivery, our dedicated team works tirelessly to ensure your goods arrive safely and on time.",
    our_skills_title: "Our Skills",
    our_skills_desc:
      "At S&N LOGISTICS LLC, we understand that every shipment matters. That’s why we’ve built our reputation on reliability, transparency, and unparalleled customer service. From the moment you contact us to the final delivery, our dedicated team works tirelessly to ensure your goods arrive safely and on time.",
    skill_1: "On-Time Delivery",
    skill_2: "Global Coverage",
    skill_3: "Customer Satisfaction",
    skill_4: "Customs Clearance",
    blog_main_title: "Our Latest News",
    blog_main_desc: "Stay updated with the latest trends and insights from S&N LOGISTICS LLC.",
    blog_1_title: "The Future of Global Logistics in 2026",
    blog_1_excerpt: "Discover how AI and automation are reshaping the supply chain and what it means for international shipping.",
    blog_1_date: "March 15, 2026",
    blog_2_title: "Navigating Customs: A Beginner's Guide",
    blog_2_excerpt: "Learn the essential steps to ensure your cargo passes through border control without unnecessary delays.",
    blog_2_date: "February 28, 2026",
    blog_3_title: "Eco-Friendly Shipping Solutions",
    blog_3_excerpt: "How maritime and air freight companies are adopting green initiatives to reduce their carbon footprint.",
    blog_3_date: "January 10, 2026",
    blog_read_more: "Read More",
    blog_back_btn: "← Back to Blogs",
    links_main_title: "Useful Resources",
    links_main_desc: "Explore our essential guides and specifications for international shipping.",
    link_incoterms_title: "Incoterms",
    link_incoterms_desc: "Comprehensive guide to International Commercial Terms (FOB, CIF, EXW, etc.) and understanding buyer/seller responsibilities.",
    link_containers_title: "Container Specifications",
    link_containers_desc: "Detailed dimensions, capacities, and types of shipping containers (20ft, 40ft, HQ, Open Top) to plan your cargo loading.",
    btn_view_incoterms: "View Incoterms",
    btn_view_containers: "View Containers",
    links_cat_guide: "Guide",
    links_cat_specs: "Specifications",
    links_back_btn: "← Back to Resources",
    incoterms_h1: "Understanding Incoterms 2020",
    incoterms_p1: "Incoterms (International Commercial Terms) are predefined commercial terms published by the International Chamber of Commerce (ICC). They are widely used in international commercial transactions or procurement processes and clearly communicate the tasks, costs, and risks associated with the transportation and delivery of goods.",
    incoterms_h2_fob: "FOB (Free On Board)",
    incoterms_p_fob: "Under FOB terms, the seller bears all costs and risks up to the point the goods are loaded on board the vessel. The buyer assumes responsibility from that point forward, including freight costs, insurance, and import duties.",
    incoterms_h2_cif: "CIF (Cost, Insurance, and Freight)",
    incoterms_p_cif: "CIF means that the seller delivers the goods on board the vessel or procures the goods already so delivered. The risk of loss of or damage to the goods passes when the goods are on board the vessel. The seller must contract for and pay the costs and freight necessary to bring the goods to the named port of destination, and also contract for insurance cover against the buyer's risk.",
    incoterms_h2_exw: "EXW (Ex Works)",
    incoterms_p_exw: "EXW represents the minimum obligation for the seller. The seller simply has to make the goods available, suitably packaged, at the specified place (usually the seller's factory or depot). The buyer assumes all risks and costs associated with loading, transporting, and clearing the goods for export.",
    incoterms_quote: '"Choosing the right Incoterm is critical for preventing disputes and precisely allocating shipping costs and liabilities between buyers and sellers."',
    containers_h1: "Global Shipping Container Types",
    containers_p1: "Standardizing shipping containers revolutionized global trade. Understanding the exact dimensions and weight capacities of standard containers is essential for maximizing space and ensuring safe transit of your cargo.",
    containers_h2_20: "20' Standard Container (20ft Dry)",
    containers_p_20: "The standard 20-foot container is the most common unit for general purpose cargo. It typically carries heavy commodities like machinery, metal, or dense consumer goods.<br><strong>Internal dimensions:</strong> 5.9m (L) x 2.35m (W) x 2.39m (H)<br><strong>Capacity:</strong> ~33.2 cubic meters<br><strong>Max Payload:</strong> ~28,200 kg",
    containers_h2_40: "40' Standard Container (40ft Dry)",
    containers_p_40: "Ideal for voluminous but lighter cargo. Used heavily in the textile, electronics, and consumer retail industries.<br><strong>Internal dimensions:</strong> 12.03m (L) x 2.35m (W) x 2.39m (H)<br><strong>Capacity:</strong> ~67.7 cubic meters<br><strong>Max Payload:</strong> ~26,600 kg",
    containers_h2_40hq: "40' High Cube (40HC)",
    containers_p_40hq: "Offers an extra foot of height compared to the standard 40ft, making it perfect for light, bulky cargo or overheight industrial equipment.<br><strong>Internal dimensions:</strong> 12.03m (L) x 2.35m (W) x 2.69m (H)<br><strong>Capacity:</strong> ~76.3 cubic meters<br><strong>Max Payload:</strong> ~26,580 kg",
    containers_quote: '"Properly matching your cargo volume and density to the correct container guarantees optimal freight rates and zero transit delays."',
    blog_cat_industry: "Industry News",
    blog_cat_guide: "Guides",
    blog_cat_environment: "Environment",
    b1_p1: "In recent years, the logistics industry has undergone massive transformations. As we move through 2026, artificial intelligence and automation are no longer just buzzwords—they are the backbone of modern supply chains.",
    b1_p2: "Companies are now leveraging machine learning algorithms to predict shipping routes, optimize fuel consumption, and manage warehouse inventory with pinpoint accuracy. This not only reduces costs but significantly cuts down delivery times.",
    b1_quote: '"Innovation distinguishes between a leader and a follower in the shipping industry."',
    b1_p3: "At S&N LOGISTICS LLC, we are fully committed to integrating these cutting-edge technologies to ensure that our clients receive the most efficient, transparent, and reliable service possible on a global scale.",
    b2_p1: "Navigating international customs can often feel like a maze of paperwork, regulations, and unexpected fees. However, with the right preparation, the customs clearance process can be smooth and hassle-free.",
    b2_p2: "The most critical step is ensuring all documentation is accurate. This includes the commercial invoice, packing list, and bill of lading. Missing or incorrect information is the number one cause of border delays.",
    b2_p3: "Partnering with an experienced freight forwarder like S&N LOGISTICS LLC means you have experts handling the red tape for you. We ensure full compliance with international trade laws so your cargo arrives without interruption.",
    b3_p1: "As global trade continues to expand, so does the environmental impact of the shipping industry. To combat global warming, logistics companies are increasingly adopting sustainable and eco-friendly practices.",
    b3_p2: "From utilizing alternative marine fuels like LNG and biofuels to optimizing flight paths for reduced emissions, the industry is making significant strides towards a greener future. Electric delivery fleets are also transforming last-mile logistics.",
    b3_p3: "S&N LOGISTICS LLC is proud to support these green initiatives. We are continuously optimizing our robust shipping networks to lower our carbon footprint while maintaining the lightning-fast delivery speeds our clients expect.",
  },

  ka: {
    nav_home: "მთავარი",
    nav_about: "ჩვენს შესახებ",
    nav_links: "ბმულები",
    nav_blogs: "ბლოგი",

    hero_title: "S&N LOGISTICS LLC",
    hero_subtitle: "თქვენი სანდო პარტნიორი საერთაშორისო გადაზიდვებში",
    hero_desc:
      "ჩვენ გთავაზობთ სრულ ლოგისტიკურ მომსახურებას საჰაერო, საზღვაო, სარკინიგზო და სახმელეთო გზებით.",
    btn_started: "დაწყება",
    btn_learn: "ვრცლად",

    serv_main_title: "ჩვენი სერვისები",
    serv_main_desc: "თქვენს საჭიროებებზე მორგებული სრული გადაზიდვის სერვისი",

    serv_sea_title: "საზღვაო გადაზიდვა",
    serv_sea_desc: "ეფექტური საზღვაო გადაზიდვა დიდი მოცულობის ტვირთებისთვის",
    serv_sea_li1: "FCL და LCL გადაზიდვები",
    serv_sea_li2: "პორტიდან პორტამდე / კარიდან კარამდე",
    serv_sea_li3: "საბაჟო გაფორმება",
    serv_sea_li4: "ტვირთის დაზღვევა",

    serv_air_title: "საჰაერო გადაზიდვა",
    serv_air_desc: "სწრაფი და საიმედო ავია გადაზიდვა",
    serv_air_li1: "ექსპრეს მიწოდება",
    serv_air_li2: "ნაკრები ტვირთები",
    serv_air_li3: "სახიფათო ტვირთების გადაზიდვა",
    serv_air_li4: "რეალურ დროში მონიტორინგი",

    serv_rail_title: "სარკინიგზო გადაზიდვა",
    serv_rail_desc: "ეფექტური სარკინიგზო ტრანსპორტი კონტინენტებს შორის",
    serv_rail_li1: "საკონტეინერო გადაზიდვა",
    serv_rail_li2: "ინტერმოდალური სერვისები",
    serv_rail_li3: "საზღვრისკვეთა და მიწოდება",
    serv_rail_li4: "ბიუჯეტური გადაწყვეტილებები",

    serv_road_title: "სახმელეთო გადაზიდვა",
    serv_road_desc: "მოქნილი მიწოდება კარიდან კარამდე",
    serv_road_li1: "ადგილობრივი და საერთაშორისო",
    serv_road_li2: "ტემპერატურული რეჟიმის დაცვა",
    serv_road_li3: "სპეციალიზებული ტრანსპორტი",
    serv_road_li4: "საბოლოო დანიშნულებამდე მიტანა",

    gal_title: "გალერეა",
    gal_desc: "ჩვენი ოპერაციები მსოფლიოს მასშტაბით",
    gal_img1_title: "ტვირთის დატვირთვა",
    gal_img1_desc: "უსაფრთხო შეფუთვის გადაწყვეტილებები",
    gal_img2_title: "კონტეინერის შევსება",
    gal_img2_desc: "ტვირთის პროფესიონალური დამუშავება",
    gal_img3_title: "ხარისხის ინსპექცია",
    gal_img3_desc: "უსაფრთხოებისა და სტანდარტების შემოწმება",
    gal_img4_title: "მძიმე ტექნიკის ტრანსპორტირება",
    gal_img4_desc: "სპეციალიზებული ტექნიკის გადაზიდვა",
    gal_img5_title: "ავტომობილების ლოგისტიკა",
    gal_img5_desc: "მანქანების უსაფრთხო ტრანსპორტირება",
    gal_img6_title: "ტვირთის ზედამხედველობა",
    gal_img6_desc: "დატვირთვის პროცესის მონიტორინგი",

    cont_title: "დაგვიკავშირდით",
    cont_desc: "გაქვთ კითხვები? მოგვწერეთ ან დაგვირეკეთ.",
    cont_info_title: "საკონტაქტო ინფორმაცია",
    cont_addr_label: "მისამართი",
    cont_phone_label: "ტელეფონი",
    cont_email_label: "ელ-ფოსტა",

    footer_contact_title: "კონტაქტი",
    footer_addr_val: "ფოთი, საქართველო",
    footer_links_title: "სასარგებლო ბმულები",
    footer_rights: "© 2026 შპს S&N Logistics. ყველა უფლება დაცულია.",

    about_main_title: "ჩვენს შესახებ",
    about_main_desc:
      "S&N LOGISTICS LLC არის დინამიური და სწრაფად მზარდი ლოგისტიკური კომპანია, რომელიც მდებარეობს ფოთში, საქართველოში. ჩვენ სპეციალიზებულნი ვართ კლიენტებისთვის მთელი მსოფლიოს მასშტაბით სრული გადაზიდვისა და ლოგისტიკური გადაწყვეტილებების უზრუნველყოფაში. ჩვენი მისიაა საერთაშორისო ვაჭრობის სირთულეების გამარტივება თითოეული მომხმარებლის უნიკალურ საჭიროებებზე მორგებული საიმედო, ეფექტური და ბიუჯეტური სერვისების შეთავაზებით.",
    why_choose_title: "რატომ უნდა აირჩიოთ S&N LOGISTICS LLC?",
    why_choose_desc:
      "S&N LOGISTICS LLC-ში ჩვენ გვესმის, რომ თითოეულ გადაზიდვას მნიშვნელობა აქვს. სწორედ ამიტომ ავაშენეთ ჩვენი რეპუტაცია საიმედოობაზე, გამჭვირვალობასა და მომხმარებელთა უბადლო მომსახურებაზე. ჩვენთან დაკავშირების მომენტიდან საბოლოო მიწოდებამდე, ჩვენი თავდადებული გუნდი დაუღალავად მუშაობს იმის უზრუნველსაყოფად, რომ თქვენი ტვირთი უსაფრთხოდ და დროულად მივიდეს.",
    our_skills_title: "ჩვენი უნარები",
    our_skills_desc:
      "S&N LOGISTICS LLC-ში ჩვენ გვესმის, რომ თითოეულ გადაზიდვას მნიშვნელობა აქვს. სწორედ ამიტომ ავაშენეთ ჩვენი რეპუტაცია საიმედოობაზე, გამჭვირვალობასა და მომხმარებელთა უბადლო მომსახურებაზე. ჩვენთან დაკავშირების მომენტიდან საბოლოო მიწოდებამდე, ჩვენი თავდადებული გუნდი დაუღალავად მუშაობს იმის უზრუნველსაყოფად, რომ თქვენი ტვირთი უსაფრთხოდ და დროულად მივიდეს.",
    skill_1: "დროული მიწოდება",
    skill_2: "გლობალური დაფარვა",
    skill_3: "მომხმარებლის კმაყოფილება",
    skill_4: "საბაჟო გაფორმება",
    blog_main_title: "ჩვენი უახლესი სიახლეები",
    blog_main_desc: "თვალი ადევნეთ S&N LOGISTICS LLC-ის უახლეს ტენდენციებსა და სიახლეებს.",
    blog_1_title: "გლობალური ლოგისტიკის მომავალი 2026 წელს",
    blog_1_excerpt: "აღმოაჩინეთ, თუ როგორ ცვლის ხელოვნური ინტელექტი და ავტომატიზაცია მიწოდების ჯაჭვს.",
    blog_1_date: "15 მარტი, 2026",
    blog_2_title: "საბაჟო პროცედურები: გზამკვლევი",
    blog_2_excerpt: "გაეცანით აუცილებელ ნაბიჯებს, რათა თქვენმა ტვირთმა შეუფერხებლად გაიაროს საზღვარი.",
    blog_2_date: "28 თებერვალი, 2026",
    blog_3_title: "ეკოლოგიურად სუფთა გადაზიდვები",
    blog_3_excerpt: "როგორ ნერგავენ საზღვაო და საჰაერო გადაზიდვების კომპანიები მწვანე ინიციატივებს.",
    blog_3_date: "10 იანვარი, 2026",
    blog_read_more: "ვრცლად",
    blog_back_btn: "← უკან ბლოგებზე",
    links_main_title: "სასარგებლო რესურსები",
    links_main_desc: "გაეცანით ჩვენს აუცილებელ სახელმძღვანელოებსა და სპეციფიკაციებს საერთაშორისო გადაზიდვებისთვის.",
    link_incoterms_title: "ინკოტერმს (Incoterms)",
    link_incoterms_desc: "საერთაშორისო კომერციული პირობების (FOB, CIF, EXW, და ა.შ.) სრული გზამკვლევი და მყიდველის/გამყიდველის პასუხისმგებლობების განაწილება.",
    link_containers_title: "კონტეინერის სპეციფიკაციები",
    link_containers_desc: "საკონტეინერო ტვირთების დეტალური ზომები, მოცულობები და ტიპები (20ft, 40ft, HQ, Open Top) თქვენი ტვირთის დასაგეგმად.",
    btn_view_incoterms: "ინკოტერმსის ნახვა",
    btn_view_containers: "კონტეინერების ნახვა",
    links_cat_guide: "გზამკვლევი",
    links_cat_specs: "სპეციფიკაციები",
    links_back_btn: "← უკან რესურსებზე",
    incoterms_h1: "ინკოტერმს 2020-ის გაგება",
    incoterms_p1: "Incoterms (საერთაშორისო კომერციული პირობები) არის ვაჭრობის საერთაშორისო პალატის (ICC) მიერ გამოქვეყნებული წინასწარ განსაზღვრული კომერციული ტერმინები. ისინი ფართოდ გამოიყენება საერთაშორისო კომერციულ ტრანზაქციებში. ისინი ნათლად გამოხატავენ ტვირთის გადაზიდვასა და მიწოდებასთან დაკავშირებულ ამოცანებს, ხარჯებსა და რისკებს.",
    incoterms_h2_fob: "FOB (Free On Board)",
    incoterms_p_fob: "FOB პირობების მიხედვით, გამყიდველი ეკისრება ყველა ხარჯსა და რისკს იმ მომენტამდე, სანამ საქონელი არ დაიტვირთება გემზე. ამის შემდეგ მყიდველი იღებს პასუხისმგებლობას, მათ შორის ტრანსპორტირების ხარჯებზე, დაზღვევასა და შემოტანის გადასახადებზე.",
    incoterms_h2_cif: "CIF (Cost, Insurance, and Freight)",
    incoterms_p_cif: "CIF ნიშნავს, რომ გამყიდველი აწვდის საქონელს გემზე. საქონლის დაკარგვის ან დაზიანების რისკი გადადის მყიდველზე, როდესაც საქონელი გემზეა. გამყიდველმა უნდა გადაიხადოს ტრანსპორტირებისა და დაზღვევის ხარჯები დანიშნულების პორტამდე.",
    incoterms_h2_exw: "EXW (Ex Works)",
    incoterms_p_exw: "EXW წარმოადგენს გამყიდველის მინიმალურ ვალდებულებას. გამყიდველმა უბრალოდ უნდა გახადოს საქონელი ხელმისაწვდომი, სათანადოდ შეფუთული, მითითებულ ადგილას (ჩვეულებრივ გამყიდველის ქარხანაში). მყიდველი იღებს ყველა რისკს და ხარჯს ექსპორტისთვის, დატვირთვისა და ტრანსპორტირებისთვის.",
    incoterms_quote: '"სწორი Incoterm-ის არჩევა გადამწყვეტია დავების თავიდან ასაცილებლად და ტრანსპორტირების ხარჯების ზუსტი განაწილებისთვის."',
    containers_h1: "გლობალური გადაზიდვის კონტეინერების ტიპები",
    containers_p1: "გადაზიდვის კონტეინერების სტანდარტიზაციამ მოახდინა რევოლუცია გლობალურ ვაჭრობაში. სტანდარტული კონტეინერების ზუსტი ზომებისა და წონის ტევადობის გაგება აუცილებელია სივრცის მაქსიმიზაციისთვის და თქვენი ტვირთის უსაფრთხოდ ტრანზიტისთვის.",
    containers_h2_20: "20' სტანდარტული კონტეინერი (20ft Dry)",
    containers_p_20: "სტანდარტული 20-ფუტიანი კონტეინერი ყველაზე გავრცელებული ერთეულია ზოგადი დანიშნულების ტვირთისთვის. გადააქვთ მძიმე საქონელი, როგორიცაა ტექნიკა, ლითონი ან მჭიდრო სამომხმარებლო საქონელი.<br><strong>შიდა ზომები:</strong> 5.9m (L) x 2.35m (W) x 2.39m (H)<br><strong>მოცულობა:</strong> ~33.2 კუბური მეტრი<br><strong>მაქს. დატვირთვა:</strong> ~28,200 კგ",
    containers_h2_40: "40' სტანდარტული კონტეინერი (40ft Dry)",
    containers_p_40: "იდეალურია მოცულობითი, მაგრამ მსუბუქი ტვირთისთვის. ფართოდ გამოიყენება ტექსტილის, ელექტრონიკის და საცალო მრეწველობაში.<br><strong>შიდა ზომები:</strong> 12.03m (L) x 2.35m (W) x 2.39m (H)<br><strong>მოცულობა:</strong> ~67.7 კუბური მეტრი<br><strong>მაქს. დატვირთვა:</strong> ~26,600 კგ",
    containers_h2_40hq: "40' High Cube (40HC)",
    containers_p_40hq: "სტანდარტულ 40 ფუტიან კონტეინერთან შედარებით გთავაზობთ დამატებით სიმაღლეს, რაც მას სრულყოფილს ხდის მსუბუქი, მოცულობითი ტვირთისთვის.<br><strong>შიდა ზომები:</strong> 12.03m (L) x 2.35m (W) x 2.69m (H)<br><strong>მოცულობა:</strong> ~76.3 კუბური მეტრი<br><strong>მაქს. დატვირთვა:</strong> ~26,580 კგ",
    containers_quote: '"თქვენი ტვირთის მოცულობისა და სიმკვრივის სწორ კონტეინერთან შეხამება გარანტირებულია ოპტიმალური ტრანსპორტირებისთვის და შეფერხებების გარეშე ტრანზიტისთვის."',
    blog_cat_industry: "ინდუსტრიის სიახლეები",
    blog_cat_guide: "გზამკვლევი",
    blog_cat_environment: "გარემოს დაცვა",
    b1_p1: "ბოლო წლებში ლოგისტიკის ინდუსტრიამ მასიური ტრანსფორმაცია განიცადა. 2026 წელს ხელოვნური ინტელექტი და ავტომატიზაცია თანამედროვე მიწოდების ჯაჭვის ხერხემლად იქცა.",
    b1_p2: "კომპანიები ახლა იყენებენ მანქანური სწავლების ალგორითმებს მარშრუტების საპროგნოზოდ, საწვავის მოხმარების ოპტიმიზაციისა და საწყობების ზუსტი მართვისთვის. ეს არა მხოლოდ ამცირებს ხარჯებს, არამედ მნიშვნელოვნად ამცირებს მიწოდების დროს.",
    b1_quote: '"ინოვაცია განასხვავებს ლიდერსა და მიმდევარს გადაზიდვების ინდუსტრიაში."',
    b1_p3: "S&N LOGISTICS LLC სრულად არის მოწოდებული დანერგოს ეს უახლესი ტექნოლოგიები, რათა ჩვენმა კლიენტებმა მიიღონ ყველაზე ეფექტური, გამჭვირვალე და საიმედო მომსახურება გლობალურად.",
    b2_p1: "საერთაშორისო საბაჟოზე გავლა ხშირად ჰგავს დოკუმენტების და რეგულაციების ლაბირინთს. თუმცა, სწორი მომზადებით, განბაჟების პროცესი შეიძლება იყოს შეუფერხებელი.",
    b2_p2: "ყველაზე კრიტიკული ნაბიჯი დოკუმენტაციის სიზუსტეა. ეს მოიცავს კომერციულ ინვოისს, შეფუთვის სიას და ზედნადებს.",
    b2_p3: "გამოცდილ ექსპედიტორთან თანამშრომლობა, როგორიცაა S&N LOGISTICS LLC, ნიშნავს რომ ექსპერტები გაუმკლავდებიან ბიუროკრატიას თქვენს მაგივრად. ჩვენ უზრუნველვყოფთ სრულ შესაბამისობას საერთაშორისო კანონმდებლობასთან.",
    b3_p1: "რაც უფრო ფართოვდება გლობალური ვაჭრობა, იზრდება გადაზიდვების ინდუსტრიის გარემოზე ზემოქმედებაც. გლობალურ დათბობასთან საბრძოლველად, ლოგისტიკური კომპანიები სულ უფრო ხშირად ნერგავენ ეკოლოგიურად სუფთა პრაქტიკას.",
    b3_p2: "ალტერნატიული საწვავის გამოყენებიდან დაწყებული ფრენის მარშრუტების ოპტიმიზაციამდე ემისიების შესამცირებლად, ინდუსტრია მნიშვნელოვან ნაბიჯებს დგამს ეკოლოგიური მომავლისკენ.",
    b3_p3: "S&N LOGISTICS LLC ამაყობს ამ მწვანე ინიციატივების მხარდაჭერით. ჩვენ მუდმივად ვაუმჯობესებთ ჩვენს ქსელებს, რათა შევამციროთ ნახშირბადის კვალი და შევინარჩუნოთ მიწოდების ელვისებური სისწრაფე.",
  },

  ru: {
    nav_home: "Главная",
    nav_about: "О нас",
    nav_links: "Ссылки",
    nav_blogs: "Блоги",

    hero_title: "S&N LOGISTICS LLC",
    hero_subtitle: "Ваш надежный партнер в международных перевозках",
    hero_desc:
      "Мы предоставляем комплексные логистические решения для авиа, морских, железнодорожных и автоперевозок.",
    btn_started: "Начать",
    btn_learn: "Подробнее",

    serv_main_title: "Наши услуги",
    serv_main_desc:
      "Комплексные решения по доставке, адаптированные к вашим потребностям",

    serv_sea_title: "Морские перевозки",
    serv_sea_desc: "Экономичная морская доставка больших объемов грузов",
    serv_sea_li1: "FCL и LCL перевозки",
    serv_sea_li2: "Порт-Порт / Дверь-Дверь",
    serv_sea_li3: "Таможенное оформление",
    serv_sea_li4: "Страхование грузов",

    serv_air_title: "Авиаперевозки",
    serv_air_desc: "Быстрая и надежная авиаперевозка срочных грузов",
    serv_air_li1: "Экспресс доставка",
    serv_air_li2: "Сборные грузы",
    serv_air_li3: "Перевозка опасных грузов",
    serv_air_li4: "Отслеживание в реальном времени",

    serv_rail_title: "Ж/Д Перевозки",
    serv_rail_desc: "Эффективные железнодорожные перевозки через континенты",
    serv_rail_li1: "Контейнерные перевозки",
    serv_rail_li2: "Интермодальные услуги",
    serv_rail_li3: "Трансграничная доставка",
    serv_rail_li4: "Выгодные решения",

    serv_road_title: "Автоперевозки",
    serv_road_desc: "Гибкая доставка от двери до двери",
    serv_road_li1: "Местные и международные",
    serv_road_li2: "Температурный режим",
    serv_road_li3: "Специализированный транспорт",
    serv_road_li4: "Доставка последней мили",

    gal_title: "Галерея",
    gal_desc: "Наши операции по всему миру",
    gal_img1_title: "Погрузка груза",
    gal_img1_desc: "Решения для надежной упаковки",
    gal_img2_title: "Загрузка контейнера",
    gal_img2_desc: "Профессиональная обработка грузов",
    gal_img3_title: "Контроль качества",
    gal_img3_desc: "Проверка безопасности и соответствия",
    gal_img4_title: "Перевозка тяжелой техники",
    gal_img4_desc: "Перевозка спецтехники",
    gal_img5_title: "Логистика автомобилей",
    gal_img5_desc: "Безопасная перевозка автомобилей",
    gal_img6_title: "Контроль груза",
    gal_img6_desc: "Мониторинг процесса погрузки",

    cont_title: "Связаться с нами",
    cont_desc: "Есть вопросы? Мы будем рады ответить.",
    cont_info_title: "Контактная информация",
    cont_addr_label: "Адрес",
    cont_phone_label: "Телефон",
    cont_email_label: "Email",

    footer_contact_title: "Контакты",
    footer_addr_val: "Поти, Грузия",
    footer_links_title: "Полезные ссылки",
    footer_rights: "© 2026 ООО S&N Logistics. Все права защищены.",

    about_main_title: "О нас",
    about_main_desc:
      "S&N LOGISTICS LLC — это динамичная и быстрорастущая логистическая компания, базирующаяся в Поти, Грузия. Мы специализируемся на предоставлении комплексных решений по доставке и логистике клиентам по всему миру. Наша миссия — упростить сложности международной торговли, предлагая надежные, эффективные и экономичные услуги, адаптированные к уникальным потребностям каждого клиента.",
    why_choose_title: "Почему выбирают S&N LOGISTICS LLC?",
    why_choose_desc:
      "В S&N LOGISTICS LLC мы понимаем, что каждая отправка имеет значение. Вот почему мы построили нашу репутацию на надежности, прозрачности и непревзойденном обслуживании клиентов. С момента вашего обращения к нам до окончательной доставки наша преданная команда неустанно работает над тем, чтобы ваши товары были доставлены в целости и в срок.",
    our_skills_title: "Наши навыки",
    our_skills_desc:
      "В S&N LOGISTICS LLC мы понимаем, что каждая отправка имеет значение. Вот почему мы построили нашу репутацию на надежности, прозрачности и непревзойденном обслуживании клиентов. С момента вашего обращения к нам до окончательной доставки наша преданная команда неустанно работает над тем, чтобы ваши товары были доставлены в целости и в срок.",
    skill_1: "Своевременная доставка",
    skill_2: "Глобальное покрытие",
    skill_3: "Удовлетворенность клиентов",
    skill_4: "Таможенное оформление",
    blog_main_title: "Наши последние новости",
    blog_main_desc: "Следите за последними тенденциями и новостями от S&N LOGISTICS LLC.",
    blog_1_title: "Будущее глобальной логистики в 2026 году",
    blog_1_excerpt: "Узнайте, как ИИ и автоматизация меняют цепочку поставок и международные перевозки.",
    blog_1_date: "15 марта 2026",
    blog_2_title: "Таможенное оформление: Руководство",
    blog_2_excerpt: "Изучите основные шаги, чтобы ваш груз прошел пограничный контроль без задержек.",
    blog_2_date: "28 февраля 2026",
    blog_3_title: "Экологичные решения для доставки",
    blog_3_excerpt: "Как компании внедряют зеленые инициативы для снижения углеродного следа.",
    blog_3_date: "10 января 2026",
    blog_read_more: "Читать далее",
    blog_back_btn: "← Вернуться к блогам",
    links_main_title: "Полезные ресурсы",
    links_main_desc: "Ознакомьтесь с нашими руководствами и спецификациями для международных перевозок.",
    link_incoterms_title: "Инкотермс (Incoterms)",
    link_incoterms_desc: "Полное руководство по международным коммерческим терминам (FOB, CIF, EXW и т.д.) и распределению ответственности.",
    link_containers_title: "Спецификации контейнеров",
    link_containers_desc: "Подробные размеры, вместимость и типы контейнеров (20ft, 40ft, HQ, Open Top) для планирования погрузки вашего груза.",
    btn_view_incoterms: "Смотреть Инкотермс",
    btn_view_containers: "Смотреть контейнеры",
    links_cat_guide: "Руководство",
    links_cat_specs: "Спецификации",
    links_back_btn: "← Вернуться к ресурсам",
    incoterms_h1: "Понимание Инкотермс 2020",
    incoterms_p1: "Инкотермс (Международные коммерческие условия) — это стандартизированные коммерческие термины, публикуемые Международной торговой палатой (ICC). Они широко используются в процессе закупа и международных коммерческих сделках, четко определяя задачи, затраты и риски, связанные с доставкой грузов.",
    incoterms_h2_fob: "FOB (Свободно на борту)",
    incoterms_p_fob: "На условиях FOB продавец несет все расходы и риски до момента погрузки товара на борт судна. С этого момента ответственность, расходы на фрахт, страхование и импортные пошлины берет на себя покупатель.",
    incoterms_h2_cif: "CIF (Стоимость, страхование и фрахт)",
    incoterms_p_cif: "CIF означает, что продавец доставляет товар на борт судна. Риск утраты или повреждения товара переходит на покупателя, когда товар находится на борту. Продавец обязан оплатить расходы, фрахт и страхование, необходимые для доставки товара в названный порт назначения.",
    incoterms_h2_exw: "EXW (Франко завод)",
    incoterms_p_exw: "EXW представляет собой минимальные обязательства для продавца. Продавец просто должен предоставить товар, надлежащим образом упакованный, в указанном месте (обычно на заводе продавца). Покупатель берет на себя все риски и расходы по погрузке, транспортировке и таможенной очистке.",
    incoterms_quote: '"Выбор правильного Инкотермс имеет решающее значение для предотвращения споров и точного распределения транспортных расходов и обязательств между покупателями и продавцами."',
    containers_h1: "Глобальные типы морских контейнеров",
    containers_p1: "Стандартизация транспортных контейнеров произвела революцию в мировой торговле. Понимание точных размеров и грузоподъемности стандартных контейнеров необходимо для максимального использования пространства и обеспечения безопасной транспортировки.",
    containers_h2_20: "20-футовый стандартный контейнер (20ft Dry)",
    containers_p_20: "Стандартный 20-футовый контейнер является наиболее распространенным для грузов общего назначения. В нем обычно перевозятся тяжелые грузы, такие как металл, оборудование или плотные товары широкого потребления.<br><strong>Внутренние размеры:</strong> 5.9м (Д) x 2.35м (Ш) x 2.39м (В)<br><strong>Вместимость:</strong> ~33.2 куб. метра<br><strong>Макс. нагрузка:</strong> ~28,200 кг",
    containers_h2_40: "40-футовый стандартный контейнер (40ft Dry)",
    containers_p_40: "Идеально подходит для объемных, но более легких грузов. Широко используется в текстильной и электронной промышленности.<br><strong>Внутренние размеры:</strong> 12.03м (Д) x 2.35м (Ш) x 2.39m (В)<br><strong>Вместимость:</strong> ~67.7 куб. метра<br><strong>Макс. нагрузка:</strong> ~26,600 кг",
    containers_h2_40hq: "40-футовый High Cube (40HC)",
    containers_p_40hq: "В отличие от стандартного 40-футового, контейнер 40HC имеет дополнительный фут высоты, что делает его идеальным для легких, громоздких грузов.<br><strong>Внутренние размеры:</strong> 12.03м (Д) x 2.35м (Ш) x 2.69м (В)<br><strong>Вместимость:</strong> ~76.3 куб. метра<br><strong>Макс. нагрузка:</strong> ~26,580 кг",
    containers_quote: '"Правильный подбор объема и типа контейнера гарантирует оптимальные ставки фрахта и отсутствие задержек в пути."',
    blog_cat_industry: "Новости отрасли",
    blog_cat_guide: "Руководства",
    blog_cat_environment: "Экология",
    b1_p1: "В последние годы логистическая отрасль претерпела масштабные изменения. В 2026 году искусственный интеллект и автоматизация стали основой современных цепочек поставок.",
    b1_p2: "Компании используют алгоритмы машинного обучения для прогнозирования маршрутов, оптимизации расхода топлива и точного управления складами. Это снижает затраты и ускоряет доставку.",
    b1_quote: '"Инновации отличают лидера от последователя в сфере судоходства."',
    b1_p3: "В S&N LOGISTICS LLC мы стремимся внедрять эти передовые технологии, чтобы наши клиенты получали самое эффективное, прозрачное и надежное обслуживание в глобальном масштабе.",
    b2_p1: "Таможенное оформление может показаться лабиринтом из документов и правил. Однако при правильной подготовке этот процесс проходит гладко и без проблем.",
    b2_p2: "Самый важный шаг — это точность документации. Это включает коммерческий инвойс, упаковочный лист и коносамент. Ошибки в документах — главная причина задержек.",
    b2_p3: "Сотрудничество с опытной логистической компанией, такой как S&N LOGISTICS LLC, означает, что эксперты решают все бюрократические вопросы за вас. Мы гарантируем полное соблюдение международных законов.",
    b3_p1: "С расширением мировой торговли растет и воздействие отрасли на окружающую среду. Чтобы бороться с глобальным потеплением, логистические компании все чаще применяют экологически чистые методы.",
    b3_p2: "От использования альтернативного топлива до оптимизации маршрутов полетов для снижения выбросов — отрасль делает большие шаги к более зеленому будущему.",
    b3_p3: "S&N LOGISTICS LLC гордится поддержкой этих зеленых инициатив. Мы постоянно оптимизируем наши сети, чтобы снизить углеродный след, сохраняя при этом молниеносную скорость доставки.",
  },
};

const languageSelect = document.getElementById("select-leng");

function changeLanguage(lang) {
  const elements = document.querySelectorAll("[data-key]");

  elements.forEach((element) => {
    const key = element.getAttribute("data-key");

    if (translations[lang] && translations[lang][key]) {
      element.innerText = translations[lang][key];
    }
  });

  localStorage.setItem("selectedLanguage", lang);
}

languageSelect.addEventListener("change", (event) => {
  changeLanguage(event.target.value);
});

document.addEventListener("DOMContentLoaded", () => {
  const savedLang = localStorage.getItem("selectedLanguage") || "en";

  languageSelect.value = savedLang;

  changeLanguage(savedLang);

  const burgerMenu = document.getElementById("burger-menu");
  const navLink = document.querySelector(".link");

  if (burgerMenu && navLink) {
    burgerMenu.addEventListener("click", () => {
      navLink.classList.toggle("active");
    });
  }
});
